a = input('Digite algo:')
print('o tipo primitivo desse valor é', type(a))
print('Só tem espaços?', a.isspace())
print('é um numero?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('é alfanumerico?', a.isalnum())
print('Está em maiúsculas?', a.isupper())
print('Está em minusculas?', a.islower())
print('Está capitalizada?', a.istitle())